# Choisir une image Python
FROM python:3.12-slim

# Créer dossier de travail
WORKDIR /app

# Pour envirnonnement Python
ENV PYTHONUNBUFFERED=1

# Copier seulement requirements.txt d’abord
COPY requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste du projet
COPY . .

# Commande par défaut
CMD ["python3", "-m", "src.worker.dlq_monitor"]
