name: Deploy ETL to Azure

on:
  push:
    branches:
      - main

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  IMAGE_NAME: data-migration
  RG_NAME: ${{ secrets.RG_NAME }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      #1.
      - name: Checkout main repo
        uses: actions/checkout@v3 

      # 2.
      - name: Checkout ADF publish branch
        uses: actions/checkout@v3
        with:
          ref: adf_publish
          path: adf_publish

      # 3.
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4.
      - name: Build Docker image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest .

      # 5.
      - name: Login to ACR
        run: az acr login --name $ACR_NAME

      # 6.
      - name: Push Docker image
        run: docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

      # 7. 
      - name: Deploy Azure Data Factory (ARM)
        run: |
          az deployment group create \
            --resource-group $RG_NAME \
            --template-file adf_publish/ARMTemplateForFactory.json \
            --parameters adf_publish/ARMTemplateParametersForFactory.json

      # 8.
      - name: Run ADF pipeline
        run: |
          az datafactory pipeline create-run \
            --factory-name $(jq -r '.parameters.factoryName.value' adf_publish/ARMTemplateParametersForFactory.json) \
            --resource-group $RG_NAME \
            --name pipeline-migration

      - name: Debug files
        run: |
          echo "=== ROOT ==="
          ls -R
          echo "=== ADF ==="
          ls -R adf_publish
